# SPDX-License-Identifier: GPL-2.0-or-later
# This is an auto-generated file. Do not edit!!
# Generated by:
# /tmp/go-build2398032822/b001/exe/part_id_gen NVL lp5 src/mainboard/google/atria/variants/atria/memory src/mainboard/google/atria/variants/atria/memory/mem_parts_used.txt

SPD_SOURCES =
SPD_SOURCES += spd/lp5/set-0/spd-11.hex      # ID = 0(0b0000)  Parts = H58G56BK8BX068
