/* SPDX-License-Identifier: GPL-2.0-only */

#include <soc/gpio.h>

#include "include/gpio.h"

/* Pad configuration was generated automatically using intelp2m utility */
static const struct pad_config gpio_table[] = {
	PAD_CFG_NF(GPP_A0, NONE, PLTRST, GPIO),
	/* GPP_A1 - LAD0 */
	PAD_CFG_NF(GPP_A1, NONE, PLTRST, NF1),
	/* GPP_A2 - LAD1 */
	PAD_CFG_NF(GPP_A2, NONE, PLTRST, NF1),
	/* GPP_A3 - LAD2 */
	PAD_CFG_NF(GPP_A3, NONE, PLTRST, NF1),
	/* GPP_A4 - LAD3 */
	PAD_CFG_NF(GPP_A4, NONE, PLTRST, NF1),
	/* GPP_A5 - LFRAME# */
	PAD_CFG_NF(GPP_A5, NONE, PLTRST, NF1),
	/* GPP_A6 - SERIRQ */
	PAD_CFG_NF(GPP_A6, NONE, PLTRST, NF1),
	/* GPP_A7 - PIRQA# */
	PAD_CFG_NF(GPP_A7, NONE, PLTRST, NF1),
	/* GPP_A8 - CLKRUN# */
	PAD_CFG_NF(GPP_A8, DN_5K, PLTRST, NF1),
	/* GPP_A9 - CLKOUT_LPC0 */
	PAD_CFG_NF(GPP_A9, NONE, PLTRST, NF1),
	/* GPP_A10 - CLKOUT_LPC1 */
	PAD_CFG_NF(GPP_A10, DN_5K, PLTRST, NF1),
	/* GPP_A11 - PME# */
	PAD_CFG_NF(GPP_A11, NONE, PLTRST, NF1),
	PAD_CFG_GPO(GPP_A12, 0, PLTRST),
	/* GPP_A13 - SUSWARN#/SUSPWRDNACK */
	PAD_CFG_NF(GPP_A13, NONE, DEEP, NF1),
	/* GPP_A14 - SUS_STAT# */
	PAD_CFG_NF(GPP_A14, NONE, DEEP, NF1),
	/* GPP_A15 - SUSACK# */
	PAD_CFG_NF(GPP_A15, NONE, DEEP, NF1),
	/* GPP_A16 - CLKOUT_48 */
	PAD_CFG_NF(GPP_A16, NONE, PLTRST, NF1),
	PAD_CFG_GPO(GPP_A17, 1, PLTRST),
	PAD_CFG_GPO(GPP_A18, 1, PLTRST),
	PAD_CFG_NF(GPP_A19, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_A20, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_A21, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_A22, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_A23, NONE, PLTRST, GPIO),

	/* ------- GPIO Group GPP_B ------- */
	PAD_CFG_GPO(GPP_B0, 1, PLTRST),
	PAD_CFG_GPO(GPP_B1, 1, PLTRST),
	PAD_CFG_GPO(GPP_B2, 1, PLTRST),
	PAD_CFG_NF(GPP_B3, NONE, PLTRST, GPIO),
	PAD_CFG_GPO(GPP_B4, 1, PLTRST),
	// PAD_CFG_NF(GPP_B5, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_B6, 1, PLTRST),
	PAD_CFG_NF(GPP_B7, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_B8, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_B9, NONE, PLTRST, GPIO),
	PAD_CFG_GPO(GPP_B10, 1, PLTRST),
	PAD_CFG_GPO(GPP_B11, 1, PLTRST),
	/* GPP_B12 - SLP_S0# */
	PAD_CFG_NF(GPP_B12, NONE, PLTRST, NF1),
	/* GPP_B13 - PLTRST# */
	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1),
	/* GPP_B14 - SPKR */
	PAD_CFG_NF(GPP_B14, DN_20K, PLTRST, NF1),
	PAD_CFG_GPO(GPP_B15, 1, PLTRST),
	PAD_CFG_GPO(GPP_B16, 1, PLTRST),
	PAD_CFG_GPO(GPP_B17, 1, DEEP),
	PAD_CFG_GPO(GPP_B18, 0, PLTRST),
	PAD_CFG_GPO(GPP_B19, 1, PLTRST),
	PAD_CFG_GPO(GPP_B20, 1, PLTRST),
	PAD_CFG_GPI_TRIG_OWN(GPP_B21, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPO(GPP_B22, 0, PLTRST),
	PAD_CFG_GPO(GPP_B23, 0, PLTRST),

	/* ------- GPIO Community 1 ------- */
	/* ------- GPIO Group GPP_C ------- */
	/* GPP_C0 - SMBCLK */
	PAD_CFG_NF(GPP_C0, NONE, DEEP, NF1),
	/* GPP_C1 - SMBDATA */
	PAD_CFG_NF(GPP_C1, NONE, DEEP, NF1),
	/* GPP_C2 - GPIO */
	PAD_CFG_GPO(GPP_C2, 1, PLTRST),
	/* GPP_C3 - SML0CLK */
	PAD_CFG_NF(GPP_C3, NONE, DEEP, NF1),
	/* GPP_C4 - SML0DATA */
	PAD_CFG_NF(GPP_C4, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_C5, 0, PLTRST),
	PAD_CFG_GPO(GPP_C6, 1, PLTRST),
	PAD_CFG_GPO(GPP_C7, 1, PLTRST),
	PAD_CFG_GPO(GPP_C8, 1, PLTRST),
	PAD_CFG_GPO(GPP_C9, 1, PLTRST),
	PAD_CFG_GPO(GPP_C10, 1, PLTRST),
	PAD_CFG_NF(GPP_C11, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_C12, NONE, PLTRST, GPIO),
	PAD_CFG_GPO(GPP_C13, 1, PLTRST),
	PAD_CFG_GPI_TRIG_OWN(GPP_C14, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_NF(GPP_C15, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_C16, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_C17, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_C18, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_C19, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_C20, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_C21, NONE, PLTRST, GPIO),
	PAD_CFG_GPO(GPP_C22, 1, PLTRST),
	PAD_CFG_GPO(GPP_C23, 1, PLTRST),

	/* ------- GPIO Group GPP_D ------- */
	PAD_CFG_GPI_TRIG_OWN(GPP_D0, NONE, RSMRST, OFF, ACPI),
	PAD_CFG_GPO(GPP_D1, 1, PLTRST),
	PAD_CFG_GPI_TRIG_OWN(GPP_D2, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPO(GPP_D3, 1, PLTRST),
	PAD_CFG_GPI_TRIG_OWN(GPP_D4, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPO(GPP_D5, 1, PLTRST),
	PAD_CFG_GPO(GPP_D6, 1, PLTRST),
	PAD_CFG_GPO(GPP_D7, 1, PLTRST),
	PAD_CFG_GPO(GPP_D8, 1, PLTRST),
	PAD_CFG_GPI_TRIG_OWN(GPP_D9, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_D10, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPO(GPP_D11, 1, PLTRST),
	PAD_CFG_GPO(GPP_D12, 1, PLTRST),
	PAD_CFG_GPO(GPP_D13, 1, PLTRST),
	PAD_CFG_GPO(GPP_D14, 1, PLTRST),
	PAD_CFG_GPI_TRIG_OWN(GPP_D15, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPO(GPP_D16, 1, PLTRST),
	/* GPP_D17 - DMIC_CLK1 */
	PAD_CFG_NF(GPP_D17, NONE, PLTRST, NF1),
	/* GPP_D18 - DMIC_DATA1 */
	PAD_CFG_NF(GPP_D18, NONE, PLTRST, NF1),
	/* GPP_D19 - DMIC_CLK0 */
	PAD_CFG_NF(GPP_D19, NONE, PLTRST, NF1),
	/* GPP_D20 - DMIC_DATA0 */
	PAD_CFG_NF(GPP_D20, NONE, PLTRST, NF1),
	PAD_CFG_GPO(GPP_D21, 1, PLTRST),
	PAD_CFG_GPO(GPP_D22, 1, PLTRST),
	PAD_CFG_GPI_TRIG_OWN(GPP_D23, NONE, PLTRST, OFF, ACPI),

	/* ------- GPIO Group GPP_G ------- */
	PAD_CFG_GPO(GPP_G0, 1, PLTRST),
	PAD_CFG_GPO(GPP_G1, 1, PLTRST),
	PAD_CFG_GPO(GPP_G2, 1, PLTRST),
	PAD_CFG_GPO(GPP_G3, 1, PLTRST),
	PAD_CFG_GPO(GPP_G4, 1, PLTRST),
	PAD_CFG_GPO(GPP_G5, 1, PLTRST),
	PAD_CFG_GPO(GPP_G6, 1, PLTRST),
	PAD_CFG_GPO(GPP_G7, 1, PLTRST),

	/* ------- GPIO Group GPD ------- */
	PAD_CFG_NF(GPD0, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPD1, NONE, PLTRST, GPIO),
	/* GPD2 - LAN_WAKE# */
	PAD_CFG_NF(GPD2, NONE, RSMRST, NF1),
	/* GPD3 - PRWBTN# */
	PAD_CFG_NF(GPD3, NONE, RSMRST, NF1),
	/* GPD4 - SLP_S3# */
	PAD_CFG_NF(GPD4, NONE, RSMRST, NF1),
	/* GPD5 - SLP_S4# */
	PAD_CFG_NF(GPD5, NONE, RSMRST, NF1),
	/* GPD6 - SLP_A# */
	PAD_CFG_NF(GPD6, NONE, RSMRST, NF1),
	PAD_CFG_GPO(GPD7, 1, PLTRST),
	/* GPD8 - SUSCLK */
	PAD_CFG_NF(GPD8, NONE, RSMRST, NF1),
	/* GPD9 - SLP_WLAN# */
	PAD_CFG_NF(GPD9, NONE, RSMRST, NF1),
	/* GPD10 - SLP_S5# */
	PAD_CFG_NF(GPD10, NONE, RSMRST, NF1),
	/* GPD11 - LANPHYPC */
	PAD_CFG_NF(GPD11, NONE, RSMRST, NF1),

	/* ------- GPIO Community 3 ------- */
	/* ------- GPIO Group GPP_K ------- */
	PAD_CFG_NF(GPP_K0, NONE, RSMRST, GPIO),
	PAD_CFG_NF(GPP_K1, NONE, RSMRST, GPIO),
	PAD_CFG_GPO(GPP_K2, 1, PLTRST),
	PAD_CFG_GPO(GPP_K3, 1, PLTRST),
	PAD_CFG_GPO(GPP_K4, 1, PLTRST),
	PAD_CFG_GPO(GPP_K5, 0, RSMRST),
	PAD_CFG_GPO(GPP_K6, 0, RSMRST),
	PAD_CFG_GPO(GPP_K7, 0, RSMRST),
	PAD_CFG_GPO(GPP_K8, 1, PLTRST),
	PAD_CFG_GPO(GPP_K9, 1, PLTRST),
	PAD_CFG_GPO(GPP_K10, 1, PLTRST),
	PAD_CFG_GPO(GPP_K11, 1, PLTRST),
	PAD_CFG_GPO(GPP_K12, 1, PLTRST),
	PAD_CFG_NF(GPP_K13, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_K14, NONE, PLTRST, GPIO),
	PAD_CFG_GPO(GPP_K15, 1, PLTRST),
	PAD_CFG_GPO(GPP_K16, 1, PLTRST),
	PAD_CFG_GPO(GPP_K17, 1, PLTRST),
	PAD_CFG_GPO(GPP_K18, 1, PLTRST),
	PAD_CFG_GPO(GPP_K19, 1, PLTRST),
	PAD_CFG_GPO(GPP_K20, 1, PLTRST),
	PAD_CFG_GPO(GPP_K21, 1, PLTRST),
	PAD_CFG_GPO(GPP_K22, 1, PLTRST),
	PAD_CFG_GPO(GPP_K23, 1, PLTRST),

	/* ------- GPIO Group GPP_H ------- */
	/* SRCCLKREQ6 */
	PAD_CFG_NF(GPP_H0, NONE, PLTRST, GPIO),
	/* SRCCLKREQ7 */
	PAD_CFG_NF(GPP_H1, NONE, PLTRST, GPIO),
	/* SRCCLKREQ8 */
	PAD_CFG_NF(GPP_H2, NONE, PLTRST, GPIO),
	/* SRCCLKREQ9 */
	PAD_CFG_NF(GPP_H3, NONE, PLTRST, NF1),
	/* SRCCLKREQ10 */
	PAD_CFG_NF(GPP_H4, NONE, DEEP, NF1),
	/* SRCCLKREQ11 */
	PAD_CFG_NF(GPP_H5, NONE, PLTRST, GPIO),
	/* SRCCLKREQ12 */
	PAD_CFG_NF(GPP_H6, NONE, PLTRST, GPIO),
	/* SRCCLKREQ13 */
	PAD_CFG_NF(GPP_H7, NONE, PLTRST, GPIO),
	/* SRCCLKREQ14 */
	PAD_CFG_NF(GPP_H8, NONE, DEEP, GPIO),
	/* SRCCLKREQ15 */
	PAD_CFG_NF(GPP_H9, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_H10, 1, PLTRST),
	PAD_CFG_GPO(GPP_H11, 1, PLTRST),
	PAD_CFG_GPO(GPP_H12, 0, PLTRST),
	PAD_CFG_GPO(GPP_H13, 1, PLTRST),
	PAD_NC(GPP_H14, NONE),
	PAD_CFG_GPO(GPP_H15, 1, PLTRST),
	/* PCIE_SMB_CLK */
	PAD_CFG_GPI_TRIG_OWN(GPP_H16, NONE, PLTRST, OFF, ACPI),
	/* PCIE_SMB_DATA */
	PAD_CFG_GPI_TRIG_OWN(GPP_H17, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPI_TRIG_OWN(GPP_H18, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_NF(GPP_H19, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_H20, NONE, PLTRST, GPIO),
	PAD_CFG_GPO(GPP_H21, 1, PLTRST),
	PAD_CFG_GPO(GPP_H22, 1, PLTRST),
	PAD_CFG_NF(GPP_H23, NONE, RSMRST, GPIO),

	/* ------- GPIO Group GPP_E ------- */
	/* GPP_E0 - SATAXPCIE0 */
	PAD_CFG_NF(GPP_E0, NONE, PLTRST, NF1),
	/* GPP_E1 - SATAXPCIE1 - M.2 SATA/PCIe detect */
	PAD_CFG_GPI(GPP_E1, NONE, PLTRST),
	/* GPP_E2 - SATAXPCIE2 */
	PAD_CFG_GPO(GPP_E2, 1, PLTRST),
	/* GPP_E3 - CPU_GP0 */
	PAD_CFG_NF(GPP_E3, NONE, PLTRST, GPIO),
	PAD_CFG_NF(GPP_E4, NONE, RSMRST, NF1),
	/* GPP_E5 - SATA_DEVSLP1 */
	PAD_CFG_NF(GPP_E5, NONE, RSMRST, NF1),
	PAD_CFG_NF(GPP_E6, NONE, RSMRST, NF1),
	PAD_CFG_GPO(GPP_E7, 1, PLTRST),
	/* GPP_E8 - SATA_LED# */
	PAD_CFG_NF(GPP_E8, UP_5K, PLTRST, NF1),
	/* GPP_E9 - USB2_OC0# */
	PAD_CFG_NF(GPP_E9, NONE, PLTRST, NF1),
	PAD_CFG_GPO(GPP_E10, 1, PLTRST),
	PAD_CFG_GPO(GPP_E11, 1, PLTRST),
	PAD_CFG_NF(GPP_E12, NONE, PLTRST, NF1),

	/* ------- GPIO Group GPP_F ------- */
	/* GPP_F0 - SATAXPCIE3 */
	PAD_CFG_NF(GPP_F0, UP_5K, PLTRST, NF1),
	/* GPP_F1 - SATAXPCIE4 */
	PAD_CFG_NF(GPP_F1, UP_5K, PLTRST, NF1),
	PAD_CFG_NF(GPP_F2, NONE, PLTRST, GPIO),
	PAD_CFG_GPO(GPP_F3, 1, PLTRST),
	PAD_CFG_GPO(GPP_F4, 1, PLTRST),
	PAD_CFG_NF(GPP_F5, NONE, RSMRST, NF1),
	PAD_CFG_NF(GPP_F6, NONE, RSMRST, NF1),
	PAD_CFG_NF(GPP_F7, NONE, RSMRST, NF1),
	PAD_CFG_GPO(GPP_F8, 1, PLTRST),
	PAD_CFG_GPO(GPP_F9, 1, PLTRST),
	/* Wi-Fi Unblock (Set to Input, let card pull high) */
	PAD_CFG_GPI(GPP_F10, NONE, PLTRST),
	/* Bluetooth Unblock (Output High) */
	PAD_CFG_GPO(GPP_F11, 1, PLTRST),
	PAD_CFG_GPO(GPP_F12, 0, RSMRST),
	PAD_CFG_GPO(GPP_F13, 0, RSMRST),
	/* GPP_F14 - PS_ON# */
	PAD_CFG_NF(GPP_F14, NONE, PLTRST, NF2),
	PAD_CFG_GPO(GPP_F15, 1, PLTRST),
	PAD_CFG_GPO(GPP_F16, 1, PLTRST),
	PAD_CFG_GPO(GPP_F17, 1, PLTRST),
	PAD_CFG_GPO(GPP_F18, 1, PLTRST),
	PAD_CFG_GPO(GPP_F19, 1, PLTRST),
	PAD_CFG_GPO(GPP_F20, 1, DEEP),
	PAD_CFG_GPO(GPP_F21, 1, DEEP),
	PAD_CFG_GPO(GPP_F22, 1, PLTRST),
	PAD_CFG_GPO(GPP_F23, 1, PLTRST),

	/* ------- GPIO Group GPP_I ------- */
	/* GPP_I0 - DDPB_HPD0 */
	PAD_CFG_NF(GPP_I0, NONE, PLTRST, NF1),
	/* GPP_I1 - DDPB_HPD1 */
	PAD_CFG_NF(GPP_I1, NONE, PLTRST, NF1),
	/* GPP_I2 - DDPB_HPD2 */
	PAD_CFG_NF(GPP_I2, NONE, PLTRST, NF1),
	PAD_CFG_GPO(GPP_I3, 1, PLTRST),
	/* GPP_I4 - EDP_HPD */
	PAD_CFG_NF(GPP_I4, NONE, PLTRST, NF1),
	/* GPP_I5 - DDPB_CTRLCLK */
	PAD_CFG_NF(GPP_I5, NONE, PLTRST, NF1),
	/* GPP_I6 - DDPB_CTRLDATA */
	PAD_CFG_NF(GPP_I6, NONE, PLTRST, NF1),
	/* GPP_I7 - DDPC_CTRLCLK */
	PAD_CFG_NF(GPP_I7, NONE, PLTRST, NF1),
	/* GPP_I8 - DDPC_CTRLDATA */
	PAD_CFG_NF(GPP_I8, NONE, PLTRST, NF1),
	/* GPP_I9 - DDPD_CTRLCLK */
	PAD_CFG_NF(GPP_I9, NONE, PLTRST, NF1),
	/* GPP_I10 - DDPD_CTRLDATA */
	PAD_CFG_NF(GPP_I10, NONE, PLTRST, NF1),
	PAD_CFG_GPO(GPP_I11, 1, PLTRST),
	PAD_CFG_GPO(GPP_I12, 1, PLTRST),
	PAD_CFG_GPO(GPP_I13, 1, PLTRST),
	PAD_CFG_GPO(GPP_I14, 1, PLTRST),

	/* ------- GPIO Group GPP_J ------- */
	PAD_CFG_GPO(GPP_J0, 1, PLTRST),
	/* GPP_J1 - CPU_C10_GATE# */
	PAD_CFG_NF(GPP_J1, NONE, PLTRST, NF2),
	PAD_CFG_GPO(GPP_J2, 1, PLTRST),
	PAD_CFG_GPO(GPP_J3, 1, PLTRST),
	PAD_CFG_NF(GPP_J4, NONE, PLTRST, GPIO),
	PAD_CFG_GPO(GPP_J5, 1, PLTRST),
	PAD_CFG_NF(GPP_J6, NONE, PLTRST, GPIO),
	PAD_CFG_GPO(GPP_J7, 1, PLTRST),
	PAD_CFG_GPO(GPP_J8, 1, PLTRST),
	PAD_CFG_GPI_TRIG_OWN(GPP_J9, NONE, PLTRST, OFF, ACPI),
	PAD_CFG_GPO(GPP_J10, 1, PLTRST),
	PAD_CFG_GPO(GPP_J11, 1, PLTRST),
};

void mainboard_configure_gpios(void)
{
	gpio_configure_pads(gpio_table, ARRAY_SIZE(gpio_table));
}
