/** @file
 *
 * This file is automatically generated.
 *
 */

#ifndef __FSPSUPD_H__
#define __FSPSUPD_H__

#include <FspUpd.h>

#pragma pack(1)


typedef struct {
	/** Offset 0x0020**/	uint32_t                    emmc0_mode;
	/** Offset 0x0024**/	uint8_t                     reserved_for_later[12];
	/** Offset 0x0030**/	uint8_t                     dxio_descriptor0[16];
	/** Offset 0x0040**/	uint8_t                     dxio_descriptor1[16];
	/** Offset 0x0050**/	uint8_t                     dxio_descriptor2[16];
	/** Offset 0x0060**/	uint8_t                     dxio_descriptor3[16];
	/** Offset 0x0070**/	uint8_t                     dxio_descriptor4[16];
	/** Offset 0x0080**/	uint8_t                     dxio_descriptor5[16];
	/** Offset 0x0090**/	uint32_t                    ddi_descriptor0;
	/** Offset 0x0094**/	uint32_t                    ddi_descriptor1;
	/** Offset 0x0098**/	uint32_t                    ddi_descriptor2;
	/** Offset 0x009C**/	uint32_t                    ddi_descriptor3;
	/** Offset 0x00A0**/	uint8_t                     UnusedUpdSpace0[128];
	/** Offset 0x0120**/	uint16_t                    UpdTerminator;
} FSP_S_CONFIG;

/** Fsp S UPD Configuration
**/
typedef struct {
	/** Offset 0x0000**/	FSP_UPD_HEADER              FspUpdHeader;
	/** Offset 0x0020**/	FSP_S_CONFIG                FspsConfig;
} FSPS_UPD;

#pragma pack()

#endif
