verstage-$(CONFIG_DRIVERS_I2C_LED_LP5562) += led_lp5562.c
verstage-$(CONFIG_DRIVERS_I2C_LED_LP5562) += led_lp5562_programs.c

ramstage-$(CONFIG_DRIVERS_I2C_LED_LP5562) += led_lp5562.c
ramstage-$(CONFIG_DRIVERS_I2C_LED_LP5562) += led_lp5562_programs.c
