/* SPDX-License-Identifier: GPL-2.0-only */

#include <gpio.h>
#include "gpio.h"

/* GPIO pins used by coreboot should be initialized in bootblock */

static const struct soc_amd_gpio gpio_set_stage_reset[] = {
	/* TPM CS */
	PAD_NF(GPIO_29, SPI_TPM_CS_L, PULL_UP),
	/* TPM IRQ */
	PAD_INT(GPIO_130, PULL_UP, EDGE_LOW, STATUS_DELIVERY),
	/* SPI_ROM_REQ */
	PAD_NF(GPIO_67, SPI_ROM_REQ, PULL_NONE),
	/* SPI_ROM_GNT */
	PAD_NF(GPIO_76, SPI_ROM_GNT, PULL_NONE),
	/* KBRST_L */
	PAD_NF(GPIO_21, KBRST_L, PULL_NONE),

	/* ESPI_CS_L */
	PAD_NF(GPIO_30, ESPI_CS_L, PULL_UP),
	/* ESPI_SOC_CLK */
	PAD_NF(GPIO_77, SPI1_CLK, PULL_NONE),
	/* ESPI_DATA0 */
	PAD_NF(GPIO_81, SPI1_DAT0, PULL_NONE),
	/* ESPI_DATA1 */
	PAD_NF(GPIO_80, SPI1_DAT1, PULL_NONE),
	/* ESPI_DATA2 */
	PAD_NF(GPIO_68, SPI1_DAT2, PULL_NONE),
	/* ESPI_DATA3 */
	PAD_NF(GPIO_69, SPI1_DAT3, PULL_NONE),
	/* ESPI_ALERT_L */
	PAD_NF(GPIO_22, ESPI_ALERT_D1, PULL_NONE),
	/* EC SCI */
	PAD_SCI(GPIO_6, PULL_UP, EDGE_LOW),

	/* Deassert PCIe Reset lines */
	/* PCIE_RST0_L */
	PAD_NFO(GPIO_26, PCIE_RST0_L, HIGH),
	/* PCIE_RST1_L */
	PAD_NFO(GPIO_27, PCIE_RST1_L, HIGH),
	/* M2_SSD0_RST_L */
	PAD_GPO(GPIO_78, HIGH),

	/* FANIN0 */
	PAD_NF(GPIO_84, FANIN0, PULL_NONE),
	/* FANOUT0 */
	PAD_NF(GPIO_85, FANOUT0, PULL_NONE),
	/* PC BEEP - DNI */
	PAD_NFO(GPIO_91, SPKR, LOW),

	/* UART2_RXD */
	PAD_NF(GPIO_136, UART2_RXD, PULL_NONE),
	/* UART2_TXD */
	PAD_NF(GPIO_138, UART2_TXD, PULL_NONE),
	/* UART0_RXD */
	PAD_NF(GPIO_141, UART0_RXD, PULL_NONE),
	/* UART0_TXD */
	PAD_NF(GPIO_143, UART0_TXD, PULL_NONE),
#if CONFIG(UART_0_1_2_3_TWO_WIRE)
	/* UART3_TXD */
	PAD_NF(GPIO_135, UART3_TXD, PULL_NONE),
	/* UART3_RXD */
	PAD_NF(GPIO_137, UART3_RXD, PULL_NONE),
	/* UART1_TXD */
	PAD_NF(GPIO_140, UART1_TXD, PULL_NONE),
	/* UART1_RXD */
	PAD_NF(GPIO_142, UART1_RXD, PULL_NONE),
#else
	/* UART2_CTS_L */
	PAD_NF(GPIO_135, UART2_CTS_L, PULL_NONE),
	/* UART2_RTS_L */
	PAD_NF(GPIO_137, UART2_RTS_L, PULL_NONE),
	/* UART0_CTS_L */
	PAD_NF(GPIO_140, UART0_CTS_L, PULL_NONE),
	/* UART0_RTS_L */
	PAD_NF(GPIO_142, UART0_RTS_L, PULL_NONE),
#endif

	/* CPLD_TDO_SOC_1V8 / MDIO2_SCL */
	PAD_GPO(GPIO_9, LOW),
	/* CPLD_TMS_SOC / USB_OSC3_L */
	PAD_GPO(GPIO_24, LOW),
	/* LPC_RST_L (CPLD RST)*/
	PAD_NF(GPIO_32, LPC_RST_L, PULL_DOWN),
	/* CPLD_TCK_SOC */
	PAD_NF(GPIO_74,GPIOxx, PULL_DOWN),
	/* CPLD_TDI_SOC */
	PAD_NF(GPIO_79, GPIOxx, PULL_DOWN),
	/* USB2_HDR_P0/1_SMI */
	PAD_SCI(GPIO_40, PULL_UP, EDGE_LOW),
};

void mainboard_program_early_gpios(void)
{
	gpio_configure_pads(gpio_set_stage_reset, ARRAY_SIZE(gpio_set_stage_reset));
}
